name: CI/CD self hosted pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: self-runner/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('self-runner/**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install
        working-directory: self-runner

  run-code:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Run build
        run: npm run build
        working-directory: self-runner

      - name: Install serve
        run: npm install -g serve

      - name: Serve production build
        run: serve -s build -l 3000
        working-directory: self-runner
